## MarigoldMusic.gd - original procedural Mexican folk-inspired score player.
## Plays looping WAV compositions generated by tools/make_music.py
## (Karplus-Strong guitar, trumpet-ish lead, hand-drum percussion).
## Also synthesizes live plucked notes at runtime for the guitar station.
extends Node
class_name MarigoldMusic

const AUDIO_DIR := "res://assets/audio/"

## Beats per minute of each generated mood loop (from tools/make_music.py).
## Drives get_beat_phase() for beat-synced choreography (v0.5.0).
const BEAT_BPM := {
	"tender": 60.0,
	"wondrous": 70.0,
	"festive": 125.0, # 6/8: eighth = 0.24 s, beat = 2 eighths
	"finale": 120.0,
}

var _players: Dictionary = {}
var _current_mood := ""
var _volume_db := -6.0
var _amb_players: Dictionary = {}
var _amb_volume_db := -14.0
var _thunder_stream: AudioStreamWAV = null


func _ready() -> void:
	for mood in ["tender", "wondrous", "festive", "finale"]:
		var p := AudioStreamPlayer.new()
		p.name = "Music_" + mood
		p.volume_db = _volume_db
		p.bus = "Master"
		add_child(p)
		_players[mood] = p
		var stream: AudioStreamWAV = load(AUDIO_DIR + mood + ".wav")
		if stream != null:
			stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
			stream.loop_begin = 0
			stream.loop_end = stream.get_data().size() / 2
			p.stream = stream


## Crossfade-free mood switch: stop current, play new loop.
func play_mood(mood: String) -> void:
	if mood == _current_mood:
		return
	stop()
	_current_mood = mood
	var p: AudioStreamPlayer = _players.get(mood)
	if p != null and p.stream != null:
		p.play()


func stop() -> void:
	for key in _players:
		(_players[key] as AudioStreamPlayer).stop()
	_current_mood = ""


func set_volume(db: float) -> void:
	_volume_db = db
	for key in _players:
		(_players[key] as AudioStreamPlayer).volume_db = db


## ---- Weather ambience (MarigoldSky, v0.4.0) ----
## Looped rain/wind beds, crossfade-free like moods. All content synthesized
## by tools/make_weather_audio.py - no licensed assets.

## Start (or keep) a looped ambience bed. kind: "rain" | "wind".
func play_ambience(kind: String) -> void:
	if kind != "rain" and kind != "wind":
		push_warning("[MarigoldMusic] unknown ambience: " + kind)
		return
	var p: AudioStreamPlayer = _amb_players.get(kind)
	if p == null:
		p = AudioStreamPlayer.new()
		p.name = "Amb_" + kind
		p.volume_db = _amb_volume_db
		p.bus = "Master"
		add_child(p)
		_amb_players[kind] = p
		var stream: AudioStreamWAV = load(AUDIO_DIR + kind + ".wav")
		if stream != null:
			stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
			stream.loop_begin = 0
			stream.loop_end = stream.get_data().size() / 2
			p.stream = stream
	if p.stream != null and not p.playing:
		p.play()


## Stop all ambience beds.
func stop_ambience() -> void:
	for key in _amb_players:
		(_amb_players[key] as AudioStreamPlayer).stop()


func set_ambience_volume(db: float) -> void:
	_amb_volume_db = db
	for key in _amb_players:
		(_amb_players[key] as AudioStreamPlayer).volume_db = db


## Duck music + ambience under the pause overlay (v0.5.0). Cheap: just
## drops the loop volumes; everything keeps playing underneath.
func set_ducked(on: bool) -> void:
	var cut := -14.0 if on else 0.0
	for key in _players:
		(_players[key] as AudioStreamPlayer).volume_db = _volume_db + cut
	for key in _amb_players:
		(_amb_players[key] as AudioStreamPlayer).volume_db = _amb_volume_db + cut


## One-shot thunder clap, volume scaled by intensity 0..1. Auto-freed.
func play_thunder(intensity: float = 1.0) -> void:
	if _thunder_stream == null:
		_thunder_stream = load(AUDIO_DIR + "thunder.wav")
	if _thunder_stream == null:
		return
	var p := AudioStreamPlayer.new()
	p.stream = _thunder_stream
	p.volume_db = lerpf(-16.0, -2.0, clampf(intensity, 0.0, 1.0))
	p.bus = "Master"
	add_child(p)
	p.play()
	p.finished.connect(p.queue_free)


## ---- Character stingers (v0.6.0) ----
## One-shot SFX for face-system demo moments, synthesized by
## tools/make_music.py (all original, <1 s, auto-freed like thunder).
## kinds: "gasp" (crowd inhale, the bow), "wink" (high KS pluck pair),
## "greet" (warm 3-note folk motif), "bow_drum" (low hand-drum + chime).
var _stinger_streams: Dictionary = {}

func play_stinger(kind: String, volume_db: float = -6.0) -> void:
	var stream: AudioStreamWAV = _stinger_streams.get(kind)
	if stream == null:
		stream = load(AUDIO_DIR + "stinger_" + kind + ".wav") as AudioStreamWAV
		if stream == null:
			push_warning("[MarigoldMusic] missing stinger: " + kind)
			return
		_stinger_streams[kind] = stream
	var p := AudioStreamPlayer.new()
	p.stream = stream
	p.volume_db = volume_db
	p.bus = "Master"
	add_child(p)
	p.play()
	p.finished.connect(p.queue_free)


## ---- Beat tracking (v0.5.0) ----
## The mood loops are fixed-tempo generated WAVs, so the beat phase can be
## derived from the playback position. 0.0 = beat start, 1.0 = next beat.
## Returns -1.0 when no mood is playing (caller should idle-dance instead).

func get_beat_phase() -> float:
	var p: AudioStreamPlayer = _players.get(_current_mood)
	if p == null or not p.playing:
		return -1.0
	var bpm: float = BEAT_BPM.get(_current_mood, 60.0)
	var pos := p.get_playback_position()
	return fmod(pos * bpm / 60.0, 1.0)


## Seconds since the current beat started (-1.0 when no mood playing).
func get_beat_time() -> float:
	var phase := get_beat_phase()
	if phase < 0.0:
		return -1.0
	var bpm: float = BEAT_BPM.get(_current_mood, 60.0)
	return phase * 60.0 / bpm


## Current mood's BPM (0.0 when nothing playing).
func get_bpm() -> float:
	var p: AudioStreamPlayer = _players.get(_current_mood)
	if p == null or not p.playing:
		return 0.0
	return BEAT_BPM.get(_current_mood, 60.0)


## Soft bell chime for photo glows / blessings: long KS decay, gentle attack.
func chime(midi_note: int, volume: float = 0.6) -> AudioStreamPlayer:
	return pluck(midi_note, volume, 2.8, 0.9992)


## Runtime Karplus-Strong plucked string for the guitar station.
## midi_note: standard MIDI number (e.g. 40=E2 .. 64=E4). Returns and plays.
## damp: feedback damping (0.996 = guitar pluck, 0.9992 = bell-like chime).
func pluck(midi_note: int, volume: float = 0.8, duration: float = 1.2, damp: float = 0.996) -> AudioStreamPlayer:
	var freq := 440.0 * pow(2.0, (midi_note - 69) / 12.0)
	var rate := 22050
	var n := int(rate * duration)
	var period := int(rate / freq)
	var buf := PackedByteArray()
	buf.resize(n * 2)
	var line := PackedFloat32Array()
	line.resize(period)
	var rng := RandomNumberGenerator.new()
	rng.randomize()
	for i in period:
		line[i] = (rng.randf() * 2.0 - 1.0) * volume
	var idx := 0
	for i in n:
		var s: float = line[idx]
		# Simple lowpass via averaging with next sample (the KS magic).
		var nxt: float = line[(idx + 1) % period]
		line[idx] = damp * 0.5 * (s + nxt)
		var v := int(clampf(s, -1.0, 1.0) * 32767.0)
		buf[i * 2] = v & 0xFF
		buf[i * 2 + 1] = (v >> 8) & 0xFF
		idx = (idx + 1) % period
	var wav := AudioStreamWAV.new()
	wav.format = AudioStreamWAV.FORMAT_16_BITS
	wav.mix_rate = rate
	wav.stereo = false
	wav.data = buf
	var p := AudioStreamPlayer.new()
	p.stream = wav
	p.volume_db = -4.0
	add_child(p)
	p.play()
	p.finished.connect(p.queue_free)
	return p
